# Generated by Django 4.1.4 on 2023-01-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bb_options_alter_bb_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[(None, 'Выберите тип объявления'), ('b', 'Продам'), ('s', 'Куплю'), ('c', 'Обменяю'), ('r', 'Rent')], default='s', max_length=1, null=True, verbose_name='Тип'),
        ),
    ]
