# Generated by Django 4.1.4 on 2023-01-19 09:44

import bboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bb_image_additionalimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalimage',
            options={'verbose_name': 'Дополнительная фото', 'verbose_name_plural': 'Дополнительные фото'},
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published'], 'verbose_name': 'Лицо', 'verbose_name_plural': 'Лица'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='bb',
            name='price',
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.bb', verbose_name='Лицо'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to=bboard.models.get_timestamp_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, upload_to=bboard.models.get_timestamp_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[(None, 'Выберите пол'), ('m', 'М'), ('w', 'Ж')], default='w', max_length=1, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Категория'),
        ),
    ]
